//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumeWCF.NumberConverterWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="NumberConverterWS.NumberConversionSoapType")]
    public interface NumberConversionSoapType {
        
        // CODEGEN: Generating message contract since element name NumberToWordsResult from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ConsumeWCF.NumberConverterWS.NumberToWordsResponse NumberToWords(ConsumeWCF.NumberConverterWS.NumberToWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWCF.NumberConverterWS.NumberToWordsResponse> NumberToWordsAsync(ConsumeWCF.NumberConverterWS.NumberToWordsRequest request);
        
        // CODEGEN: Generating message contract since element name NumberToDollarsResult from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ConsumeWCF.NumberConverterWS.NumberToDollarsResponse NumberToDollars(ConsumeWCF.NumberConverterWS.NumberToDollarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumeWCF.NumberConverterWS.NumberToDollarsResponse> NumberToDollarsAsync(ConsumeWCF.NumberConverterWS.NumberToDollarsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToWordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWords", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ConsumeWCF.NumberConverterWS.NumberToWordsRequestBody Body;
        
        public NumberToWordsRequest() {
        }
        
        public NumberToWordsRequest(ConsumeWCF.NumberConverterWS.NumberToWordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ulong ubiNum;
        
        public NumberToWordsRequestBody() {
        }
        
        public NumberToWordsRequestBody(ulong ubiNum) {
            this.ubiNum = ubiNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToWordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToWordsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ConsumeWCF.NumberConverterWS.NumberToWordsResponseBody Body;
        
        public NumberToWordsResponse() {
        }
        
        public NumberToWordsResponse(ConsumeWCF.NumberConverterWS.NumberToWordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberToWordsResult;
        
        public NumberToWordsResponseBody() {
        }
        
        public NumberToWordsResponseBody(string NumberToWordsResult) {
            this.NumberToWordsResult = NumberToWordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToDollarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollars", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ConsumeWCF.NumberConverterWS.NumberToDollarsRequestBody Body;
        
        public NumberToDollarsRequest() {
        }
        
        public NumberToDollarsRequest(ConsumeWCF.NumberConverterWS.NumberToDollarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal dNum;
        
        public NumberToDollarsRequestBody() {
        }
        
        public NumberToDollarsRequestBody(decimal dNum) {
            this.dNum = dNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberToDollarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberToDollarsResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ConsumeWCF.NumberConverterWS.NumberToDollarsResponseBody Body;
        
        public NumberToDollarsResponse() {
        }
        
        public NumberToDollarsResponse(ConsumeWCF.NumberConverterWS.NumberToDollarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberToDollarsResult;
        
        public NumberToDollarsResponseBody() {
        }
        
        public NumberToDollarsResponseBody(string NumberToDollarsResult) {
            this.NumberToDollarsResult = NumberToDollarsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NumberConversionSoapTypeChannel : ConsumeWCF.NumberConverterWS.NumberConversionSoapType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberConversionSoapTypeClient : System.ServiceModel.ClientBase<ConsumeWCF.NumberConverterWS.NumberConversionSoapType>, ConsumeWCF.NumberConverterWS.NumberConversionSoapType {
        
        public NumberConversionSoapTypeClient() {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberConversionSoapTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberConversionSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWCF.NumberConverterWS.NumberToWordsResponse ConsumeWCF.NumberConverterWS.NumberConversionSoapType.NumberToWords(ConsumeWCF.NumberConverterWS.NumberToWordsRequest request) {
            return base.Channel.NumberToWords(request);
        }
        
        public string NumberToWords(ulong ubiNum) {
            ConsumeWCF.NumberConverterWS.NumberToWordsRequest inValue = new ConsumeWCF.NumberConverterWS.NumberToWordsRequest();
            inValue.Body = new ConsumeWCF.NumberConverterWS.NumberToWordsRequestBody();
            inValue.Body.ubiNum = ubiNum;
            ConsumeWCF.NumberConverterWS.NumberToWordsResponse retVal = ((ConsumeWCF.NumberConverterWS.NumberConversionSoapType)(this)).NumberToWords(inValue);
            return retVal.Body.NumberToWordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWCF.NumberConverterWS.NumberToWordsResponse> ConsumeWCF.NumberConverterWS.NumberConversionSoapType.NumberToWordsAsync(ConsumeWCF.NumberConverterWS.NumberToWordsRequest request) {
            return base.Channel.NumberToWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWCF.NumberConverterWS.NumberToWordsResponse> NumberToWordsAsync(ulong ubiNum) {
            ConsumeWCF.NumberConverterWS.NumberToWordsRequest inValue = new ConsumeWCF.NumberConverterWS.NumberToWordsRequest();
            inValue.Body = new ConsumeWCF.NumberConverterWS.NumberToWordsRequestBody();
            inValue.Body.ubiNum = ubiNum;
            return ((ConsumeWCF.NumberConverterWS.NumberConversionSoapType)(this)).NumberToWordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumeWCF.NumberConverterWS.NumberToDollarsResponse ConsumeWCF.NumberConverterWS.NumberConversionSoapType.NumberToDollars(ConsumeWCF.NumberConverterWS.NumberToDollarsRequest request) {
            return base.Channel.NumberToDollars(request);
        }
        
        public string NumberToDollars(decimal dNum) {
            ConsumeWCF.NumberConverterWS.NumberToDollarsRequest inValue = new ConsumeWCF.NumberConverterWS.NumberToDollarsRequest();
            inValue.Body = new ConsumeWCF.NumberConverterWS.NumberToDollarsRequestBody();
            inValue.Body.dNum = dNum;
            ConsumeWCF.NumberConverterWS.NumberToDollarsResponse retVal = ((ConsumeWCF.NumberConverterWS.NumberConversionSoapType)(this)).NumberToDollars(inValue);
            return retVal.Body.NumberToDollarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumeWCF.NumberConverterWS.NumberToDollarsResponse> ConsumeWCF.NumberConverterWS.NumberConversionSoapType.NumberToDollarsAsync(ConsumeWCF.NumberConverterWS.NumberToDollarsRequest request) {
            return base.Channel.NumberToDollarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumeWCF.NumberConverterWS.NumberToDollarsResponse> NumberToDollarsAsync(decimal dNum) {
            ConsumeWCF.NumberConverterWS.NumberToDollarsRequest inValue = new ConsumeWCF.NumberConverterWS.NumberToDollarsRequest();
            inValue.Body = new ConsumeWCF.NumberConverterWS.NumberToDollarsRequestBody();
            inValue.Body.dNum = dNum;
            return ((ConsumeWCF.NumberConverterWS.NumberConversionSoapType)(this)).NumberToDollarsAsync(inValue);
        }
    }
}
